# Site settings
title: '@andreasonny83'
email: andreasonny83@gmail.com
username: andreasonny83
description: > # this means to ignore newlines until "baseurl:"
  Articles on JavaScript, Angular, Google Material Design Lite
  and more
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://andreasonny83.github.io/" # the base hostname & protocol for your site
custom_js:
  - responsive-navbar
  - main

# Build settings
markdown: kramdown
