# Site settings
title: '@andreasonny83'
email: andreasonny83@gmail.com
username: andreasonny83
description: > # this means to ignore newlines until "baseurl:"
  Articles on JavaScript, Angular, Google Material Design Lite
  and more
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://andreasonny83.github.io/" # the base hostname & protocol for your site
custom_js:
  - responsive-navbar
  - main

# Build settings
markdown: kramdown

# Settings for comments helper
# Set 'provider' to the comment provider you want to use.
# Set 'provider' to false to turn commenting off globally.
comments :
  provider : disqus
  disqus :
    short_name : andreasonny83
  livefyre :
    site_id : 123
  intensedebate :
    account : 123abc
  facebook :
    appid : 123
    num_posts: 5
    width: 580
    colorscheme: light
